#!/usr/bin/env php
<?php

defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));

require __DIR__ . '/framework/Yii.php';

\Yii::setAlias('@app', __DIR__);

$config = require __DIR__ . '/config/console.php';

$application = new \yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
